name: Daily Stock Analysis
on:
  schedule:
    - cron: '0 18 * * *'  # Runs daily at 1PM EST
  workflow_dispatch:       # Allow manual runs

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # Required for auto-commit
    
    steps:
    # 1. Checkout code
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0     # Needed for git history
    
    # 2. Set up Python
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    # 3. Install dependencies
    - name: Install packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    # 4. Run analysis with verification
    - name: Run analysis
      id: analysis
      run: |
        python analyzer.py
        # Verify results.json exists
        if [ ! -f "results.json" ]; then
          echo "::error::results.json was not created!"
          exit 1
        fi
        echo "results.json created successfully"
        echo "size=$(wc -c < results.json)" >> $GITHUB_OUTPUT
    
    # 5. Commit results (only if file was created)
    - name: Commit results
      if: steps.analysis.outputs.size > 0
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Daily stock analysis update [skip ci]"
        branch: main
        file_pattern: results.json
        token: ${{ secrets.GITHUB_TOKEN }}
    
    # 6. Debugging step (optional)
    - name: Debug info
      if: always()
      run: |
        echo "--- File list ---"
        ls -la
        echo "--- results.json content ---"
        head -n 5 results.json || echo "No results.json found"
