name: Stock Sentiment Analysis

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:  # Allow manual trigger

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Use 3.10 instead of 3.11 for better yfinance performance
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance==0.2.18 pandas matplotlib numpy transformers requests torch --no-cache-dir
        
    - name: Run analysis
      env:
        ALPHAVANTAGE_KEY: ${{ secrets.ALPHAVANTAGE_KEY }}
        NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
      run: |
        python stock_analyzer.py
        
    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: analysis-results
        path: |
          results.json
          results.html
          summary.txt
